spring.application.name=encoding-service
server.port=8083

# Kafka Broker
spring.kafka.bootstrap-servers=localhost:9092

# Consumer
spring.kafka.consumer.group-id=encoding-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# Deserializers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust packages for JSON deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages="*"

# Optional: If producer adds type headers
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# Optional: Default target type
spring.kafka.consumer.properties.spring.json.value.default.type=com.netflix.encodingservice.event.VideoUploadedEvent

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ==========================================
# AWS S3 Configuration
# ==========================================
aws.access-key=${AWS_ACCESS_KEY:your-access-key}
aws.secret-key=${AWS_SECRET_KEY:your-secret-key}
aws.region=${AWS_REGION:ap-south-1}
aws.s3.bucket-name=${AWS_BUCKET_NAME:your-bucket-name}

# ==========================================
# FFmpeg
# ==========================================
ffmpeg.path=${FFMPEG_PATH:ffmpeg}

encoding.base-paths= ${TEMP_DIR:/tmp/encoding}

# ==========================================
# Spring Boot Actuator
# ==========================================
management.endpoints.web.exposure.include=health,info