spring.application.name=streaming-service

server.port=8084

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Kafka Broker
spring.kafka.bootstrap-servers=localhost:9092

# Consumer
spring.kafka.consumer.group-id=streaming-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# Deserializers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trust packages for JSON deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages="*"

# Optional: If producer adds type headers
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# Optional: Default target type
spring.kafka.consumer.properties.spring.json.value.default.type=com.netflix.streamingservice.event.VideoEncodedEvent


# ==========================================
# AWS S3 Configuration
# ==========================================
aws.access-key=${AWS_ACCESS_KEY:your-access-key}
aws.secret-key=${AWS_SECRET_KEY:your-secret-key}
aws.region=${AWS_REGION:ap-south-1}
aws.s3.bucket-name=${AWS_BUCKET_NAME:your-bucket-name}

# presigned URL expiry
aws.s3.presigned-url-expiry=60

# ==========================================
# Spring Boot Actuator
# ==========================================
management.endpoints.web.exposure.include=health,info